### ISSUE TITLE
[FR]: Merge with stream fork

### ISSUE THREAD

**Issue by Stillhard** [nampud/ReZygisk#1]
### Description

Please merge with remote main fork😘

### Reason

Recent main fork of ReZygisk able to hide injection detection (abnormal linker state), but your fork able to bypass zemperium protection and while main fork not yet

### Confirmations

- [x] This feature is not already implemented.
- [x] I have verified that this is not a duplicate feature request.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by epidoma** [comment]
Bad linker state seems to be the only detection thats left and its fixed upstream. I hope you merge those changes in future

<img width="1080" height="2392" alt="Image" src="https://github.com/user-attachments/assets/375d00d8-7b41-4014-9da2-152b06d7748c" />

**Comment by nampud** [comment]
I don't plan to fully merge everything, but bad linker state should now be fixed by https://github.com/nampud/ReZygisk/commit/e5acbec5a53a0a76746308a0023802413a404b11

**Comment by epidoma** [comment]
Thanks for the fix.
Native detector shows environment is normal now. 
All zygisk modules work fine but for some reason i cant play my game anymore, 8 ball pool detects magisk (im on latest kernelsu next) .
Cant find anything else wrong. Idk why native says its fine but simple game refuses to start. 
Clear data/cache reinstall the game, and its still the same.
I will try to delete data/adb and start fresh when I find some time, maybe its issue on my side.
